
spring:
  mvc:
    static-path-pattern: /static/**
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:mysql://localhost:33306/hqj
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 7070